import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "ScriptHub",
    description: "Generated by create next app",
    icons: {
      icon: "/favicon.png",    // 这里声明 favicon
      shortcut: "/favicon.png",
      apple: "/favicon.png",
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <head>
            {/* 也可以在这里显式加 link 标签 */}
            <link rel="icon" href="/favicon.png" />
          </head>
          <body
            className="antialiased"
          >
          {children}
          </body>
        </html>
    );
}
