import type { Metadata } from "next";
import "./globals.css";
import "../App.css";
import "../components/AgentChat/AgentChat.css";

export const metadata: Metadata = {
    title: "ScriptHub",
    description: "Generated by create next app",
    icons: {
      icon: "/favicon.png",    // 这里声明 favicon
      shortcut: "/favicon.png",
      apple: "/favicon.png",
    },
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
          <body
            className="antialiased"
          >
          {children}
          </body>
        </html>
    );
}
