import type { Metadata } from "next";
import "./globals.css";
import "../App.css";
import "../components/AgentChat/AgentChat.css";

export const metadata: Metadata = {
    title: "ScriptHub",
    description: "Generated by create next app",
    icons: {
      icon: "/favicon.png",
      shortcut: "/favicon.png",
      apple: "/favicon.png",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
          <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            <link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=DM+Sans:wght@300;400;500&display=swap" rel="stylesheet" />
          </head>
          <body className="antialiased" suppressHydrationWarning>
            {children}
          </body>
        </html>
    );
}
